name 'fiddyspence-mconotify'
version '0.0.2'
license 'Apache 2.0'
summary 'A Puppet report handler for sending mcollective RPC messages'
project_page 'https://github.com/fiddyspence/puppet-mconotify'
